<?php

/**
 * @file application/modules/admin/views/scripts/index/index.phtml
 * La view per la pagina di index.
 *
 * @category    application
 * @package     Admin
 * @subpackage  View_Script
 * @version     $Id: index.phtml 120 2011-08-02 15:02:35Z flicofloc@gmail.com $
 */

?>
Welcome to the admin homepage.<br/><br/>
Select a page from the above menu to navigate the admin website!