<?php

/**
 * @file application/modules/admin/views/scripts/gallery/index.phtml
 * La view per l'elenco della pagine presenti nel sito (con evidenziate quelle gallery).
 *
 * @category    application
 * @package     Admin
 * @subpackage  View_Script
 * @version     $Id: index.phtml 124 2011-08-03 10:19:56Z flicofloc@gmail.com $
 */

$this->import_Css(array('backend/movable_list'));
$this->import_Css(array('js/mootools/3rdpart/mootools-tree/Css/Tree',
                        'js/mootools/3rdpart/mootools-tree/Css/Collapse',
                        'js/mootools/3rdpart/moodialog/Source/css/MooDialog'), true);

$this->import_Js(array('mootools/3rdpart/mootools-class-extras/Source/Class.Binds',
                       'mootools/3rdpart/mootools-class-extras/Source/Class.Singleton',
                       'mootools/3rdpart/mootools-tree/Source/Tree',
                       'mootools/3rdpart/mootools-tree/Source/Collapse',
                       'mootools/3rdpart/moodialog/Source/Overlay',
                       'mootools/3rdpart/moodialog/Source/MooDialog',
                       'mootools/3rdpart/moodialog/Source/MooDialog.Fx',
                       'mootools/3rdpart/moodialog/Source/MooDialog.Alert',
                       'backend/gallery'));

?>
<div class="link"><a href="<?= $this->url(array('action' => 'new', 'controller' => 'gallery', 'module' => 'admin'), 'default') ?>" title="Create an album">Create an album</a></div>
<?= $this->printUlGalleryPages($this->pages) ?>