<?php

/**
 * @file application/modules/admin/views/scripts/gallery/new.phtml
 * La view per la creazione di un album.
 *
 * @category    application
 * @package     Admin
 * @subpackage  View_Script
 * @version     $Id: new.phtml 126 2011-08-03 16:20:17Z flicofloc@gmail.com $
 */

?>
<div class="link"><a href="<?= $this->url(array('action' => 'index', 'controller' => 'gallery', 'module' => 'admin'), 'default') ?>" title="Back to list">&lt;-- Back to album list</a></div>
<?= $this->form ?>