<?php

/**
 * @file application/views/scripts/news/index.phtml
 * La view per le pagine di news.
 *
 * @category    application
 * @package     Default
 * @subpackage  View_Script
 * @version     $Id: index.phtml 88 2011-07-29 08:24:30Z flicofloc@gmail.com $
 */

?>
<?php foreach($this->thePage->News as $News) : ?>
<div class="news">
    <div class="news_title"><?= $this->escape($News->Title) ?></div>
    <div class="news_date"><?= strftime("%d/%m/%Y %H:%M", strtotime($News->Date)) ?></div>
    <div class="news_text"><?= $this->escape($News->Text) ?></div>
</div>
<?php endforeach; ?>