<?php

/**
 * @file application/views/scripts/login/recover-password.phtml
 * La view per la pagina di recupero della password (form per l'inserimento della nuova password).
 *
 * @category    application
 * @package     Default
 * @subpackage  View_Script
 * @version     $Id: recover-password.phtml 120 2011-08-02 15:02:35Z flicofloc@gmail.com $
 */

?>
<?php if(isset($this->OK)) : ?>

    <?php if($this->OK) : ?>

<div class="notify">Password was changed correctly!</div>

    <?php else : ?>

<div class="notify">An error accurred. Please re-execute the password recovery.</div>

    <?php endif; ?>

<?php else : ?>

<?= $this->form ?>

<?php endif; ?>